### ISSUE TITLE
Type error: missing a required argument 'layers'

### ISSUE THREAD

**Issue by VolkerH** [jni/affinder#24]
Just pulled the latest master branches of napari, magicgui and affinder and getting this Error when clicking the start button:

![image](https://user-images.githubusercontent.com/2210044/107577305-8efaf080-6bf2-11eb-8217-f88cfd51f4b8.png)

```
(napari) hilsenst@itservices-XPS-15-9500:~/Github/napari$ affinder 
ERROR:root:Unhandled exception:
Traceback (most recent call last):
  File "/home/hilsenst/Github/magicgui/magicgui/widgets/_bases/value_widget.py", line 44, in <lambda>
    lambda *x: self.changed(value=x[0] if x else None)
  File "/home/hilsenst/Github/magicgui/magicgui/events.py", line 603, in __call__
    self._invoke_callback(cb, event)
  File "/home/hilsenst/Github/magicgui/magicgui/events.py", line 625, in _invoke_callback
    cb_event=(cb, event),
  File "/home/hilsenst/Github/magicgui/magicgui/events.py", line 619, in _invoke_callback
    cb(event)
  File "/home/hilsenst/Github/magicgui/magicgui/widgets/_function_gui.py", line 175, in _disable_button_and_call
    self.__call__()
  File "/home/hilsenst/Github/magicgui/magicgui/widgets/_function_gui.py", line 249, in __call__
    value = self._function(*bound.args, **bound.kwargs)
  File "/home/hilsenst/Github/affinder/affinder/affinder.py", line 147, in start_affinder
    close_affinder()
  File "/home/hilsenst/Github/magicgui/magicgui/widgets/_function_gui.py", line 241, in __call__
    raise TypeError(msg) from None
TypeError: missing a required argument: 'layers' in call to 'close_affinder(layers, callback)'.
To avoid this error, you can bind a value or callback to the parameter:

    close_affinder.layers.bind(value)

Or use the 'bind' option in the magicgui decorator:

    @magicgui(layers={'bind': value})
    def close_affinder(layers, callback): ...

ERROR:root:Unhandled exception:
```

**Comment by VolkerH** [comment]
just went back to earlier versions of `affinder` (last checkin before adding save affine) and `magicgui`  of the same date and getting the same error *scratches head*. It worked for me around that time (different machine).

**Comment by VolkerH** [comment]
Nevermind, creating a fresh conda python 3.8 environment and pip installing affinder fixed it.
The other env was python 3.7, not sure whether that could have caused it?

**Comment by jni** [comment]
:shrug: if you reproduce this in a fresh enviroment feel free to reopen!
